version: '1.0'

services:
  database:
    image: brxnogoncalves/biotrace-mysql:1.0
    container_name: biotrace_mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Urubu100@
    volumes:
      - mysql_banco_data:/var/lib/mysql

volumes:
  mysql_banco_data:
